/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 21.1.2 -fPIC -O3) */

module spm(clk, rst, x, y, p);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [31:0] x;
  wire [31:0] x;
  input y;
  wire y;
  output p;
  wire p;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire \csa0.hsum2 ;
  wire \csa0.sc ;
  wire \csa0.y ;
  wire \genblk1[10].csa.hsum2 ;
  wire \genblk1[10].csa.sc ;
  wire \genblk1[10].csa.sum ;
  wire \genblk1[10].csa.y ;
  wire \genblk1[11].csa.hsum2 ;
  wire \genblk1[11].csa.sc ;
  wire \genblk1[11].csa.y ;
  wire \genblk1[12].csa.hsum2 ;
  wire \genblk1[12].csa.sc ;
  wire \genblk1[12].csa.y ;
  wire \genblk1[13].csa.hsum2 ;
  wire \genblk1[13].csa.sc ;
  wire \genblk1[13].csa.y ;
  wire \genblk1[14].csa.hsum2 ;
  wire \genblk1[14].csa.sc ;
  wire \genblk1[14].csa.y ;
  wire \genblk1[15].csa.hsum2 ;
  wire \genblk1[15].csa.sc ;
  wire \genblk1[15].csa.y ;
  wire \genblk1[16].csa.hsum2 ;
  wire \genblk1[16].csa.sc ;
  wire \genblk1[16].csa.y ;
  wire \genblk1[17].csa.hsum2 ;
  wire \genblk1[17].csa.sc ;
  wire \genblk1[17].csa.y ;
  wire \genblk1[18].csa.hsum2 ;
  wire \genblk1[18].csa.sc ;
  wire \genblk1[18].csa.y ;
  wire \genblk1[19].csa.hsum2 ;
  wire \genblk1[19].csa.sc ;
  wire \genblk1[19].csa.y ;
  wire \genblk1[1].csa.hsum2 ;
  wire \genblk1[1].csa.sc ;
  wire \genblk1[1].csa.y ;
  wire \genblk1[20].csa.hsum2 ;
  wire \genblk1[20].csa.sc ;
  wire \genblk1[20].csa.y ;
  wire \genblk1[21].csa.hsum2 ;
  wire \genblk1[21].csa.sc ;
  wire \genblk1[21].csa.y ;
  wire \genblk1[22].csa.hsum2 ;
  wire \genblk1[22].csa.sc ;
  wire \genblk1[22].csa.y ;
  wire \genblk1[23].csa.hsum2 ;
  wire \genblk1[23].csa.sc ;
  wire \genblk1[23].csa.y ;
  wire \genblk1[24].csa.hsum2 ;
  wire \genblk1[24].csa.sc ;
  wire \genblk1[24].csa.y ;
  wire \genblk1[25].csa.hsum2 ;
  wire \genblk1[25].csa.sc ;
  wire \genblk1[25].csa.y ;
  wire \genblk1[26].csa.hsum2 ;
  wire \genblk1[26].csa.sc ;
  wire \genblk1[26].csa.y ;
  wire \genblk1[27].csa.hsum2 ;
  wire \genblk1[27].csa.sc ;
  wire \genblk1[27].csa.y ;
  wire \genblk1[28].csa.hsum2 ;
  wire \genblk1[28].csa.sc ;
  wire \genblk1[28].csa.y ;
  wire \genblk1[29].csa.hsum2 ;
  wire \genblk1[29].csa.sc ;
  wire \genblk1[29].csa.y ;
  wire \genblk1[2].csa.hsum2 ;
  wire \genblk1[2].csa.sc ;
  wire \genblk1[2].csa.y ;
  wire \genblk1[30].csa.hsum2 ;
  wire \genblk1[30].csa.sc ;
  wire \genblk1[30].csa.y ;
  wire \genblk1[3].csa.hsum2 ;
  wire \genblk1[3].csa.sc ;
  wire \genblk1[3].csa.y ;
  wire \genblk1[4].csa.hsum2 ;
  wire \genblk1[4].csa.sc ;
  wire \genblk1[4].csa.y ;
  wire \genblk1[5].csa.hsum2 ;
  wire \genblk1[5].csa.sc ;
  wire \genblk1[5].csa.y ;
  wire \genblk1[6].csa.hsum2 ;
  wire \genblk1[6].csa.sc ;
  wire \genblk1[6].csa.y ;
  wire \genblk1[7].csa.hsum2 ;
  wire \genblk1[7].csa.sc ;
  wire \genblk1[7].csa.y ;
  wire \genblk1[8].csa.hsum2 ;
  wire \genblk1[8].csa.sc ;
  wire \genblk1[8].csa.y ;
  wire \genblk1[9].csa.hsum2 ;
  wire \genblk1[9].csa.sc ;
  wire \tcmp.z ;
  sky130_fd_sc_hd__inv_1 _222_ (
    .A(rst),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(\genblk1[4].csa.sc ),
    .B(\genblk1[4].csa.y ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(\genblk1[4].csa.sc ),
    .B(\genblk1[4].csa.y ),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xor2_1 _225_ (
    .A(\genblk1[4].csa.sc ),
    .B(\genblk1[4].csa.y ),
    .X(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(y),
    .B(x[4]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(_099_),
    .B(_100_),
    .Y(\genblk1[4].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(\genblk1[5].csa.sc ),
    .B(\genblk1[5].csa.y ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(x[5]),
    .B(y),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(\genblk1[5].csa.sc ),
    .B(\genblk1[5].csa.y ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xor2_1 _231_ (
    .A(\genblk1[5].csa.sc ),
    .B(\genblk1[5].csa.y ),
    .X(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _232_ (
    .A1(_102_),
    .A2(_103_),
    .B1(_101_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _233_ (
    .A(_102_),
    .B(_104_),
    .Y(\genblk1[5].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(\genblk1[6].csa.sc ),
    .B(\genblk1[6].csa.y ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(y),
    .B(x[6]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(\genblk1[6].csa.sc ),
    .B(\genblk1[6].csa.y ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xor2_1 _237_ (
    .A(\genblk1[6].csa.sc ),
    .B(\genblk1[6].csa.y ),
    .X(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _238_ (
    .A1(_106_),
    .A2(_107_),
    .B1(_105_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _239_ (
    .A(_106_),
    .B(_108_),
    .Y(\genblk1[6].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(\genblk1[7].csa.sc ),
    .B(\genblk1[7].csa.y ),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(y),
    .B(x[7]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(\genblk1[7].csa.sc ),
    .B(\genblk1[7].csa.y ),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xor2_1 _243_ (
    .A(\genblk1[7].csa.sc ),
    .B(\genblk1[7].csa.y ),
    .X(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _244_ (
    .A1(_110_),
    .A2(_111_),
    .B1(_109_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _245_ (
    .A(_110_),
    .B(_112_),
    .Y(\genblk1[7].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(\genblk1[8].csa.sc ),
    .B(\genblk1[8].csa.y ),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(y),
    .B(x[8]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(\genblk1[8].csa.sc ),
    .B(\genblk1[8].csa.y ),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(\genblk1[8].csa.sc ),
    .B(\genblk1[8].csa.y ),
    .X(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _250_ (
    .A1(_114_),
    .A2(_115_),
    .B1(_113_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _251_ (
    .A(_114_),
    .B(_116_),
    .Y(\genblk1[8].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(\genblk1[9].csa.sc ),
    .B(\genblk1[10].csa.sum ),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(y),
    .B(x[9]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _254_ (
    .A(\genblk1[9].csa.sc ),
    .B(\genblk1[10].csa.sum ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xor2_1 _255_ (
    .A(\genblk1[9].csa.sc ),
    .B(\genblk1[10].csa.sum ),
    .X(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _256_ (
    .A1(_118_),
    .A2(_119_),
    .B1(_117_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _257_ (
    .A(_118_),
    .B(_120_),
    .Y(\genblk1[9].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(\genblk1[10].csa.sc ),
    .B(\genblk1[10].csa.y ),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(y),
    .B(x[10]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(\genblk1[10].csa.sc ),
    .B(\genblk1[10].csa.y ),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xor2_1 _261_ (
    .A(\genblk1[10].csa.sc ),
    .B(\genblk1[10].csa.y ),
    .X(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _262_ (
    .A1(_122_),
    .A2(_123_),
    .B1(_121_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_122_),
    .B(_124_),
    .Y(\genblk1[10].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(\genblk1[11].csa.sc ),
    .B(\genblk1[11].csa.y ),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(y),
    .B(x[11]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _266_ (
    .A(\genblk1[11].csa.sc ),
    .B(\genblk1[11].csa.y ),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xor2_1 _267_ (
    .A(\genblk1[11].csa.sc ),
    .B(\genblk1[11].csa.y ),
    .X(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_126_),
    .A2(_127_),
    .B1(_125_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_126_),
    .B(_128_),
    .Y(\genblk1[11].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(\genblk1[12].csa.sc ),
    .B(\genblk1[12].csa.y ),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(y),
    .B(x[12]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor2_1 _272_ (
    .A(\genblk1[12].csa.sc ),
    .B(\genblk1[12].csa.y ),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xor2_1 _273_ (
    .A(\genblk1[12].csa.sc ),
    .B(\genblk1[12].csa.y ),
    .X(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _274_ (
    .A1(_130_),
    .A2(_131_),
    .B1(_129_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _275_ (
    .A(_130_),
    .B(_132_),
    .Y(\genblk1[12].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(\genblk1[13].csa.sc ),
    .B(\genblk1[13].csa.y ),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(y),
    .B(x[13]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(\genblk1[13].csa.sc ),
    .B(\genblk1[13].csa.y ),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xor2_1 _279_ (
    .A(\genblk1[13].csa.sc ),
    .B(\genblk1[13].csa.y ),
    .X(_136_)
  );
  sky130_fd_sc_hd__o21ai_0 _280_ (
    .A1(_134_),
    .A2(_135_),
    .B1(_133_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _281_ (
    .A(_134_),
    .B(_136_),
    .Y(\genblk1[13].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(\genblk1[14].csa.sc ),
    .B(\genblk1[14].csa.y ),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(y),
    .B(x[14]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(\genblk1[14].csa.sc ),
    .B(\genblk1[14].csa.y ),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_1 _285_ (
    .A(\genblk1[14].csa.sc ),
    .B(\genblk1[14].csa.y ),
    .X(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _286_ (
    .A1(_138_),
    .A2(_139_),
    .B1(_137_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _287_ (
    .A(_138_),
    .B(_140_),
    .Y(\genblk1[14].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(\genblk1[15].csa.sc ),
    .B(\genblk1[15].csa.y ),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(y),
    .B(x[15]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(\genblk1[15].csa.sc ),
    .B(\genblk1[15].csa.y ),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _291_ (
    .A(\genblk1[15].csa.sc ),
    .B(\genblk1[15].csa.y ),
    .X(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _292_ (
    .A1(_142_),
    .A2(_143_),
    .B1(_141_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _293_ (
    .A(_142_),
    .B(_144_),
    .Y(\genblk1[15].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(\genblk1[16].csa.sc ),
    .B(\genblk1[16].csa.y ),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(y),
    .B(x[16]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(\genblk1[16].csa.sc ),
    .B(\genblk1[16].csa.y ),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xor2_1 _297_ (
    .A(\genblk1[16].csa.sc ),
    .B(\genblk1[16].csa.y ),
    .X(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _298_ (
    .A1(_146_),
    .A2(_147_),
    .B1(_145_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(_146_),
    .B(_148_),
    .Y(\genblk1[16].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(\genblk1[17].csa.sc ),
    .B(\genblk1[17].csa.y ),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(y),
    .B(x[17]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _302_ (
    .A(\genblk1[17].csa.sc ),
    .B(\genblk1[17].csa.y ),
    .Y(_151_)
  );
  sky130_fd_sc_hd__xor2_1 _303_ (
    .A(\genblk1[17].csa.sc ),
    .B(\genblk1[17].csa.y ),
    .X(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _304_ (
    .A1(_150_),
    .A2(_151_),
    .B1(_149_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(_150_),
    .B(_152_),
    .Y(\genblk1[17].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(\genblk1[18].csa.sc ),
    .B(\genblk1[18].csa.y ),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(y),
    .B(x[18]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(\genblk1[18].csa.sc ),
    .B(\genblk1[18].csa.y ),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(\genblk1[18].csa.sc ),
    .B(\genblk1[18].csa.y ),
    .X(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _310_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_153_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _311_ (
    .A(_154_),
    .B(_156_),
    .Y(\genblk1[18].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(\genblk1[19].csa.sc ),
    .B(\genblk1[19].csa.y ),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(y),
    .B(x[19]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(\genblk1[19].csa.sc ),
    .B(\genblk1[19].csa.y ),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xor2_1 _315_ (
    .A(\genblk1[19].csa.sc ),
    .B(\genblk1[19].csa.y ),
    .X(_160_)
  );
  sky130_fd_sc_hd__o21ai_0 _316_ (
    .A1(_158_),
    .A2(_159_),
    .B1(_157_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(_158_),
    .B(_160_),
    .Y(\genblk1[19].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(\genblk1[20].csa.sc ),
    .B(\genblk1[20].csa.y ),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(y),
    .B(x[20]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(\genblk1[20].csa.sc ),
    .B(\genblk1[20].csa.y ),
    .Y(_163_)
  );
  sky130_fd_sc_hd__xor2_1 _321_ (
    .A(\genblk1[20].csa.sc ),
    .B(\genblk1[20].csa.y ),
    .X(_164_)
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(_162_),
    .A2(_163_),
    .B1(_161_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(_162_),
    .B(_164_),
    .Y(\genblk1[20].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(\genblk1[21].csa.sc ),
    .B(\genblk1[21].csa.y ),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(y),
    .B(x[21]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _326_ (
    .A(\genblk1[21].csa.sc ),
    .B(\genblk1[21].csa.y ),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _327_ (
    .A(\genblk1[21].csa.sc ),
    .B(\genblk1[21].csa.y ),
    .X(_168_)
  );
  sky130_fd_sc_hd__o21ai_0 _328_ (
    .A1(_166_),
    .A2(_167_),
    .B1(_165_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _329_ (
    .A(_166_),
    .B(_168_),
    .Y(\genblk1[21].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(\genblk1[22].csa.sc ),
    .B(\genblk1[22].csa.y ),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(y),
    .B(x[22]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _332_ (
    .A(\genblk1[22].csa.sc ),
    .B(\genblk1[22].csa.y ),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xor2_1 _333_ (
    .A(\genblk1[22].csa.sc ),
    .B(\genblk1[22].csa.y ),
    .X(_172_)
  );
  sky130_fd_sc_hd__o21ai_0 _334_ (
    .A1(_170_),
    .A2(_171_),
    .B1(_169_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _335_ (
    .A(_170_),
    .B(_172_),
    .Y(\genblk1[22].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(\genblk1[23].csa.sc ),
    .B(\genblk1[23].csa.y ),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(y),
    .B(x[23]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(\genblk1[23].csa.sc ),
    .B(\genblk1[23].csa.y ),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xor2_1 _339_ (
    .A(\genblk1[23].csa.sc ),
    .B(\genblk1[23].csa.y ),
    .X(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _340_ (
    .A1(_174_),
    .A2(_175_),
    .B1(_173_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _341_ (
    .A(_174_),
    .B(_176_),
    .Y(\genblk1[23].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(\genblk1[24].csa.sc ),
    .B(\genblk1[24].csa.y ),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(y),
    .B(x[24]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(\genblk1[24].csa.sc ),
    .B(\genblk1[24].csa.y ),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xor2_1 _345_ (
    .A(\genblk1[24].csa.sc ),
    .B(\genblk1[24].csa.y ),
    .X(_180_)
  );
  sky130_fd_sc_hd__o21ai_0 _346_ (
    .A1(_178_),
    .A2(_179_),
    .B1(_177_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_178_),
    .B(_180_),
    .Y(\genblk1[24].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(\genblk1[25].csa.sc ),
    .B(\genblk1[25].csa.y ),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(y),
    .B(x[25]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _350_ (
    .A(\genblk1[25].csa.sc ),
    .B(\genblk1[25].csa.y ),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _351_ (
    .A(\genblk1[25].csa.sc ),
    .B(\genblk1[25].csa.y ),
    .X(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _352_ (
    .A1(_182_),
    .A2(_183_),
    .B1(_181_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _353_ (
    .A(_182_),
    .B(_184_),
    .Y(\genblk1[25].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _354_ (
    .A(\genblk1[26].csa.sc ),
    .B(\genblk1[26].csa.y ),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(y),
    .B(x[26]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(\genblk1[26].csa.sc ),
    .B(\genblk1[26].csa.y ),
    .Y(_187_)
  );
  sky130_fd_sc_hd__xor2_1 _357_ (
    .A(\genblk1[26].csa.sc ),
    .B(\genblk1[26].csa.y ),
    .X(_188_)
  );
  sky130_fd_sc_hd__o21ai_0 _358_ (
    .A1(_186_),
    .A2(_187_),
    .B1(_185_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_186_),
    .B(_188_),
    .Y(\genblk1[26].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _360_ (
    .A(\genblk1[27].csa.sc ),
    .B(\genblk1[27].csa.y ),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(y),
    .B(x[27]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(\genblk1[27].csa.sc ),
    .B(\genblk1[27].csa.y ),
    .Y(_191_)
  );
  sky130_fd_sc_hd__xor2_1 _363_ (
    .A(\genblk1[27].csa.sc ),
    .B(\genblk1[27].csa.y ),
    .X(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _364_ (
    .A1(_190_),
    .A2(_191_),
    .B1(_189_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(_190_),
    .B(_192_),
    .Y(\genblk1[27].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(\genblk1[28].csa.sc ),
    .B(\genblk1[28].csa.y ),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(y),
    .B(x[28]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(\genblk1[28].csa.sc ),
    .B(\genblk1[28].csa.y ),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xor2_1 _369_ (
    .A(\genblk1[28].csa.sc ),
    .B(\genblk1[28].csa.y ),
    .X(_196_)
  );
  sky130_fd_sc_hd__o21ai_0 _370_ (
    .A1(_194_),
    .A2(_195_),
    .B1(_193_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(_194_),
    .B(_196_),
    .Y(\genblk1[28].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(\genblk1[29].csa.sc ),
    .B(\genblk1[29].csa.y ),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand2_1 _373_ (
    .A(y),
    .B(x[29]),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(\genblk1[29].csa.sc ),
    .B(\genblk1[29].csa.y ),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _375_ (
    .A(\genblk1[29].csa.sc ),
    .B(\genblk1[29].csa.y ),
    .X(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _376_ (
    .A1(_198_),
    .A2(_199_),
    .B1(_197_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _377_ (
    .A(_198_),
    .B(_200_),
    .Y(\genblk1[29].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(\genblk1[30].csa.sc ),
    .B(\genblk1[30].csa.y ),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(y),
    .B(x[30]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(\genblk1[30].csa.sc ),
    .B(\genblk1[30].csa.y ),
    .Y(_203_)
  );
  sky130_fd_sc_hd__xor2_1 _381_ (
    .A(\genblk1[30].csa.sc ),
    .B(\genblk1[30].csa.y ),
    .X(_204_)
  );
  sky130_fd_sc_hd__o21ai_0 _382_ (
    .A1(_202_),
    .A2(_203_),
    .B1(_201_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _383_ (
    .A(_202_),
    .B(_204_),
    .Y(\genblk1[30].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(\genblk1[1].csa.sc ),
    .B(\genblk1[1].csa.y ),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(\genblk1[1].csa.sc ),
    .B(\genblk1[1].csa.y ),
    .Y(_206_)
  );
  sky130_fd_sc_hd__xor2_1 _386_ (
    .A(\genblk1[1].csa.sc ),
    .B(\genblk1[1].csa.y ),
    .X(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _387_ (
    .A(y),
    .B(x[1]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _388_ (
    .A1(_206_),
    .A2(_208_),
    .B1(_205_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_207_),
    .B(_208_),
    .Y(\genblk1[1].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(\genblk1[2].csa.sc ),
    .B(\genblk1[2].csa.y ),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(y),
    .B(x[2]),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor2_1 _392_ (
    .A(\genblk1[2].csa.sc ),
    .B(\genblk1[2].csa.y ),
    .Y(_211_)
  );
  sky130_fd_sc_hd__xor2_1 _393_ (
    .A(\genblk1[2].csa.sc ),
    .B(\genblk1[2].csa.y ),
    .X(_212_)
  );
  sky130_fd_sc_hd__o21ai_0 _394_ (
    .A1(_210_),
    .A2(_211_),
    .B1(_209_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _395_ (
    .A(_210_),
    .B(_212_),
    .Y(\genblk1[2].csa.hsum2 )
  );
  sky130_fd_sc_hd__nand2_1 _396_ (
    .A(\genblk1[3].csa.sc ),
    .B(\genblk1[3].csa.y ),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(y),
    .B(x[3]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(\genblk1[3].csa.sc ),
    .B(\genblk1[3].csa.y ),
    .Y(_215_)
  );
  sky130_fd_sc_hd__xor2_1 _399_ (
    .A(\genblk1[3].csa.sc ),
    .B(\genblk1[3].csa.y ),
    .X(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _400_ (
    .A1(_214_),
    .A2(_215_),
    .B1(_213_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _401_ (
    .A(_214_),
    .B(_216_),
    .Y(\genblk1[3].csa.hsum2 )
  );
  sky130_fd_sc_hd__o21ai_0 _402_ (
    .A1(_098_),
    .A2(_100_),
    .B1(_097_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(\csa0.sc ),
    .B(\csa0.y ),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor2_1 _404_ (
    .A(\csa0.sc ),
    .B(\csa0.y ),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xor2_1 _405_ (
    .A(\csa0.sc ),
    .B(\csa0.y ),
    .X(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(y),
    .B(x[0]),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(_218_),
    .A2(_220_),
    .B1(_217_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor2_1 _408_ (
    .A(_219_),
    .B(_220_),
    .Y(\csa0.hsum2 )
  );
  sky130_fd_sc_hd__a21o_1 _409_ (
    .A1(y),
    .A2(x[31]),
    .B1(\tcmp.z ),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand3_1 _410_ (
    .A(y),
    .B(x[31]),
    .C(\tcmp.z ),
    .Y(_221_)
  );
  sky130_fd_sc_hd__and2_0 _411_ (
    .A(_032_),
    .B(_221_),
    .X(_031_)
  );
  sky130_fd_sc_hd__inv_1 _412_ (
    .A(rst),
    .Y(_034_)
  );
  sky130_fd_sc_hd__inv_1 _413_ (
    .A(rst),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_1 _414_ (
    .A(rst),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_1 _415_ (
    .A(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_1 _416_ (
    .A(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_1 _417_ (
    .A(rst),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_1 _418_ (
    .A(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_1 _419_ (
    .A(rst),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_1 _420_ (
    .A(rst),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_1 _421_ (
    .A(rst),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_1 _422_ (
    .A(rst),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_1 _423_ (
    .A(rst),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_1 _424_ (
    .A(rst),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_1 _425_ (
    .A(rst),
    .Y(_047_)
  );
  sky130_fd_sc_hd__inv_1 _426_ (
    .A(rst),
    .Y(_048_)
  );
  sky130_fd_sc_hd__inv_1 _427_ (
    .A(rst),
    .Y(_049_)
  );
  sky130_fd_sc_hd__inv_1 _428_ (
    .A(rst),
    .Y(_050_)
  );
  sky130_fd_sc_hd__inv_1 _429_ (
    .A(rst),
    .Y(_051_)
  );
  sky130_fd_sc_hd__inv_1 _430_ (
    .A(rst),
    .Y(_052_)
  );
  sky130_fd_sc_hd__inv_1 _431_ (
    .A(rst),
    .Y(_053_)
  );
  sky130_fd_sc_hd__inv_1 _432_ (
    .A(rst),
    .Y(_054_)
  );
  sky130_fd_sc_hd__inv_1 _433_ (
    .A(rst),
    .Y(_055_)
  );
  sky130_fd_sc_hd__inv_1 _434_ (
    .A(rst),
    .Y(_056_)
  );
  sky130_fd_sc_hd__inv_1 _435_ (
    .A(rst),
    .Y(_057_)
  );
  sky130_fd_sc_hd__inv_1 _436_ (
    .A(rst),
    .Y(_058_)
  );
  sky130_fd_sc_hd__inv_1 _437_ (
    .A(rst),
    .Y(_059_)
  );
  sky130_fd_sc_hd__inv_1 _438_ (
    .A(rst),
    .Y(_060_)
  );
  sky130_fd_sc_hd__inv_1 _439_ (
    .A(rst),
    .Y(_061_)
  );
  sky130_fd_sc_hd__inv_1 _440_ (
    .A(rst),
    .Y(_062_)
  );
  sky130_fd_sc_hd__inv_1 _441_ (
    .A(rst),
    .Y(_063_)
  );
  sky130_fd_sc_hd__inv_1 _442_ (
    .A(rst),
    .Y(_064_)
  );
  sky130_fd_sc_hd__inv_1 _443_ (
    .A(rst),
    .Y(_065_)
  );
  sky130_fd_sc_hd__inv_1 _444_ (
    .A(rst),
    .Y(_066_)
  );
  sky130_fd_sc_hd__inv_1 _445_ (
    .A(rst),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_1 _446_ (
    .A(rst),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_1 _447_ (
    .A(rst),
    .Y(_069_)
  );
  sky130_fd_sc_hd__inv_1 _448_ (
    .A(rst),
    .Y(_070_)
  );
  sky130_fd_sc_hd__inv_1 _449_ (
    .A(rst),
    .Y(_071_)
  );
  sky130_fd_sc_hd__inv_1 _450_ (
    .A(rst),
    .Y(_072_)
  );
  sky130_fd_sc_hd__inv_1 _451_ (
    .A(rst),
    .Y(_073_)
  );
  sky130_fd_sc_hd__inv_1 _452_ (
    .A(rst),
    .Y(_074_)
  );
  sky130_fd_sc_hd__inv_1 _453_ (
    .A(rst),
    .Y(_075_)
  );
  sky130_fd_sc_hd__inv_1 _454_ (
    .A(rst),
    .Y(_076_)
  );
  sky130_fd_sc_hd__inv_1 _455_ (
    .A(rst),
    .Y(_077_)
  );
  sky130_fd_sc_hd__inv_1 _456_ (
    .A(rst),
    .Y(_078_)
  );
  sky130_fd_sc_hd__inv_1 _457_ (
    .A(rst),
    .Y(_079_)
  );
  sky130_fd_sc_hd__inv_1 _458_ (
    .A(rst),
    .Y(_080_)
  );
  sky130_fd_sc_hd__inv_1 _459_ (
    .A(rst),
    .Y(_081_)
  );
  sky130_fd_sc_hd__inv_1 _460_ (
    .A(rst),
    .Y(_082_)
  );
  sky130_fd_sc_hd__inv_1 _461_ (
    .A(rst),
    .Y(_083_)
  );
  sky130_fd_sc_hd__inv_1 _462_ (
    .A(rst),
    .Y(_084_)
  );
  sky130_fd_sc_hd__inv_1 _463_ (
    .A(rst),
    .Y(_085_)
  );
  sky130_fd_sc_hd__inv_1 _464_ (
    .A(rst),
    .Y(_086_)
  );
  sky130_fd_sc_hd__inv_1 _465_ (
    .A(rst),
    .Y(_087_)
  );
  sky130_fd_sc_hd__inv_1 _466_ (
    .A(rst),
    .Y(_088_)
  );
  sky130_fd_sc_hd__inv_1 _467_ (
    .A(rst),
    .Y(_089_)
  );
  sky130_fd_sc_hd__inv_1 _468_ (
    .A(rst),
    .Y(_090_)
  );
  sky130_fd_sc_hd__inv_1 _469_ (
    .A(rst),
    .Y(_091_)
  );
  sky130_fd_sc_hd__inv_1 _470_ (
    .A(rst),
    .Y(_092_)
  );
  sky130_fd_sc_hd__inv_1 _471_ (
    .A(rst),
    .Y(_093_)
  );
  sky130_fd_sc_hd__inv_1 _472_ (
    .A(rst),
    .Y(_094_)
  );
  sky130_fd_sc_hd__inv_1 _473_ (
    .A(rst),
    .Y(_095_)
  );
  sky130_fd_sc_hd__inv_1 _474_ (
    .A(rst),
    .Y(_096_)
  );
  sky130_fd_sc_hd__dfrtp_1 _475_ (
    .CLK(clk),
    .D(\csa0.hsum2 ),
    .Q(p),
    .RESET_B(_036_)
  );
  sky130_fd_sc_hd__dfrtp_1 _476_ (
    .CLK(clk),
    .D(_000_),
    .Q(\csa0.sc ),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _477_ (
    .CLK(clk),
    .D(_032_),
    .Q(\tcmp.z ),
    .RESET_B(_038_)
  );
  sky130_fd_sc_hd__dfrtp_1 _478_ (
    .CLK(clk),
    .D(_031_),
    .Q(\genblk1[30].csa.y ),
    .RESET_B(_039_)
  );
  sky130_fd_sc_hd__dfrtp_1 _479_ (
    .CLK(clk),
    .D(\genblk1[1].csa.hsum2 ),
    .Q(\csa0.y ),
    .RESET_B(_040_)
  );
  sky130_fd_sc_hd__dfrtp_1 _480_ (
    .CLK(clk),
    .D(_011_),
    .Q(\genblk1[1].csa.sc ),
    .RESET_B(_041_)
  );
  sky130_fd_sc_hd__dfrtp_1 _481_ (
    .CLK(clk),
    .D(\genblk1[2].csa.hsum2 ),
    .Q(\genblk1[1].csa.y ),
    .RESET_B(_042_)
  );
  sky130_fd_sc_hd__dfrtp_1 _482_ (
    .CLK(clk),
    .D(_022_),
    .Q(\genblk1[2].csa.sc ),
    .RESET_B(_043_)
  );
  sky130_fd_sc_hd__dfrtp_1 _483_ (
    .CLK(clk),
    .D(\genblk1[3].csa.hsum2 ),
    .Q(\genblk1[2].csa.y ),
    .RESET_B(_044_)
  );
  sky130_fd_sc_hd__dfrtp_1 _484_ (
    .CLK(clk),
    .D(_024_),
    .Q(\genblk1[3].csa.sc ),
    .RESET_B(_045_)
  );
  sky130_fd_sc_hd__dfrtp_1 _485_ (
    .CLK(clk),
    .D(\genblk1[4].csa.hsum2 ),
    .Q(\genblk1[3].csa.y ),
    .RESET_B(_046_)
  );
  sky130_fd_sc_hd__dfrtp_1 _486_ (
    .CLK(clk),
    .D(_025_),
    .Q(\genblk1[4].csa.sc ),
    .RESET_B(_047_)
  );
  sky130_fd_sc_hd__dfrtp_1 _487_ (
    .CLK(clk),
    .D(\genblk1[5].csa.hsum2 ),
    .Q(\genblk1[4].csa.y ),
    .RESET_B(_048_)
  );
  sky130_fd_sc_hd__dfrtp_1 _488_ (
    .CLK(clk),
    .D(_026_),
    .Q(\genblk1[5].csa.sc ),
    .RESET_B(_049_)
  );
  sky130_fd_sc_hd__dfrtp_1 _489_ (
    .CLK(clk),
    .D(\genblk1[6].csa.hsum2 ),
    .Q(\genblk1[5].csa.y ),
    .RESET_B(_050_)
  );
  sky130_fd_sc_hd__dfrtp_1 _490_ (
    .CLK(clk),
    .D(_027_),
    .Q(\genblk1[6].csa.sc ),
    .RESET_B(_051_)
  );
  sky130_fd_sc_hd__dfrtp_1 _491_ (
    .CLK(clk),
    .D(\genblk1[7].csa.hsum2 ),
    .Q(\genblk1[6].csa.y ),
    .RESET_B(_052_)
  );
  sky130_fd_sc_hd__dfrtp_1 _492_ (
    .CLK(clk),
    .D(_028_),
    .Q(\genblk1[7].csa.sc ),
    .RESET_B(_053_)
  );
  sky130_fd_sc_hd__dfrtp_1 _493_ (
    .CLK(clk),
    .D(\genblk1[8].csa.hsum2 ),
    .Q(\genblk1[7].csa.y ),
    .RESET_B(_054_)
  );
  sky130_fd_sc_hd__dfrtp_1 _494_ (
    .CLK(clk),
    .D(_029_),
    .Q(\genblk1[8].csa.sc ),
    .RESET_B(_055_)
  );
  sky130_fd_sc_hd__dfrtp_1 _495_ (
    .CLK(clk),
    .D(\genblk1[9].csa.hsum2 ),
    .Q(\genblk1[8].csa.y ),
    .RESET_B(_056_)
  );
  sky130_fd_sc_hd__dfrtp_1 _496_ (
    .CLK(clk),
    .D(_030_),
    .Q(\genblk1[9].csa.sc ),
    .RESET_B(_057_)
  );
  sky130_fd_sc_hd__dfrtp_1 _497_ (
    .CLK(clk),
    .D(\genblk1[10].csa.hsum2 ),
    .Q(\genblk1[10].csa.sum ),
    .RESET_B(_058_)
  );
  sky130_fd_sc_hd__dfrtp_1 _498_ (
    .CLK(clk),
    .D(_001_),
    .Q(\genblk1[10].csa.sc ),
    .RESET_B(_059_)
  );
  sky130_fd_sc_hd__dfrtp_1 _499_ (
    .CLK(clk),
    .D(\genblk1[11].csa.hsum2 ),
    .Q(\genblk1[10].csa.y ),
    .RESET_B(_060_)
  );
  sky130_fd_sc_hd__dfrtp_1 _500_ (
    .CLK(clk),
    .D(_002_),
    .Q(\genblk1[11].csa.sc ),
    .RESET_B(_061_)
  );
  sky130_fd_sc_hd__dfrtp_1 _501_ (
    .CLK(clk),
    .D(\genblk1[12].csa.hsum2 ),
    .Q(\genblk1[11].csa.y ),
    .RESET_B(_062_)
  );
  sky130_fd_sc_hd__dfrtp_1 _502_ (
    .CLK(clk),
    .D(_003_),
    .Q(\genblk1[12].csa.sc ),
    .RESET_B(_063_)
  );
  sky130_fd_sc_hd__dfrtp_1 _503_ (
    .CLK(clk),
    .D(\genblk1[13].csa.hsum2 ),
    .Q(\genblk1[12].csa.y ),
    .RESET_B(_064_)
  );
  sky130_fd_sc_hd__dfrtp_1 _504_ (
    .CLK(clk),
    .D(_004_),
    .Q(\genblk1[13].csa.sc ),
    .RESET_B(_065_)
  );
  sky130_fd_sc_hd__dfrtp_1 _505_ (
    .CLK(clk),
    .D(\genblk1[14].csa.hsum2 ),
    .Q(\genblk1[13].csa.y ),
    .RESET_B(_066_)
  );
  sky130_fd_sc_hd__dfrtp_1 _506_ (
    .CLK(clk),
    .D(_005_),
    .Q(\genblk1[14].csa.sc ),
    .RESET_B(_067_)
  );
  sky130_fd_sc_hd__dfrtp_1 _507_ (
    .CLK(clk),
    .D(\genblk1[15].csa.hsum2 ),
    .Q(\genblk1[14].csa.y ),
    .RESET_B(_068_)
  );
  sky130_fd_sc_hd__dfrtp_1 _508_ (
    .CLK(clk),
    .D(_006_),
    .Q(\genblk1[15].csa.sc ),
    .RESET_B(_069_)
  );
  sky130_fd_sc_hd__dfrtp_1 _509_ (
    .CLK(clk),
    .D(\genblk1[16].csa.hsum2 ),
    .Q(\genblk1[15].csa.y ),
    .RESET_B(_070_)
  );
  sky130_fd_sc_hd__dfrtp_1 _510_ (
    .CLK(clk),
    .D(_007_),
    .Q(\genblk1[16].csa.sc ),
    .RESET_B(_071_)
  );
  sky130_fd_sc_hd__dfrtp_1 _511_ (
    .CLK(clk),
    .D(\genblk1[17].csa.hsum2 ),
    .Q(\genblk1[16].csa.y ),
    .RESET_B(_072_)
  );
  sky130_fd_sc_hd__dfrtp_1 _512_ (
    .CLK(clk),
    .D(_008_),
    .Q(\genblk1[17].csa.sc ),
    .RESET_B(_073_)
  );
  sky130_fd_sc_hd__dfrtp_1 _513_ (
    .CLK(clk),
    .D(\genblk1[18].csa.hsum2 ),
    .Q(\genblk1[17].csa.y ),
    .RESET_B(_074_)
  );
  sky130_fd_sc_hd__dfrtp_1 _514_ (
    .CLK(clk),
    .D(_009_),
    .Q(\genblk1[18].csa.sc ),
    .RESET_B(_075_)
  );
  sky130_fd_sc_hd__dfrtp_1 _515_ (
    .CLK(clk),
    .D(\genblk1[19].csa.hsum2 ),
    .Q(\genblk1[18].csa.y ),
    .RESET_B(_076_)
  );
  sky130_fd_sc_hd__dfrtp_1 _516_ (
    .CLK(clk),
    .D(_010_),
    .Q(\genblk1[19].csa.sc ),
    .RESET_B(_077_)
  );
  sky130_fd_sc_hd__dfrtp_1 _517_ (
    .CLK(clk),
    .D(\genblk1[20].csa.hsum2 ),
    .Q(\genblk1[19].csa.y ),
    .RESET_B(_078_)
  );
  sky130_fd_sc_hd__dfrtp_1 _518_ (
    .CLK(clk),
    .D(_012_),
    .Q(\genblk1[20].csa.sc ),
    .RESET_B(_079_)
  );
  sky130_fd_sc_hd__dfrtp_1 _519_ (
    .CLK(clk),
    .D(\genblk1[21].csa.hsum2 ),
    .Q(\genblk1[20].csa.y ),
    .RESET_B(_080_)
  );
  sky130_fd_sc_hd__dfrtp_1 _520_ (
    .CLK(clk),
    .D(_013_),
    .Q(\genblk1[21].csa.sc ),
    .RESET_B(_081_)
  );
  sky130_fd_sc_hd__dfrtp_1 _521_ (
    .CLK(clk),
    .D(\genblk1[22].csa.hsum2 ),
    .Q(\genblk1[21].csa.y ),
    .RESET_B(_082_)
  );
  sky130_fd_sc_hd__dfrtp_1 _522_ (
    .CLK(clk),
    .D(_014_),
    .Q(\genblk1[22].csa.sc ),
    .RESET_B(_083_)
  );
  sky130_fd_sc_hd__dfrtp_1 _523_ (
    .CLK(clk),
    .D(\genblk1[23].csa.hsum2 ),
    .Q(\genblk1[22].csa.y ),
    .RESET_B(_084_)
  );
  sky130_fd_sc_hd__dfrtp_1 _524_ (
    .CLK(clk),
    .D(_015_),
    .Q(\genblk1[23].csa.sc ),
    .RESET_B(_085_)
  );
  sky130_fd_sc_hd__dfrtp_1 _525_ (
    .CLK(clk),
    .D(\genblk1[24].csa.hsum2 ),
    .Q(\genblk1[23].csa.y ),
    .RESET_B(_086_)
  );
  sky130_fd_sc_hd__dfrtp_1 _526_ (
    .CLK(clk),
    .D(_016_),
    .Q(\genblk1[24].csa.sc ),
    .RESET_B(_087_)
  );
  sky130_fd_sc_hd__dfrtp_1 _527_ (
    .CLK(clk),
    .D(\genblk1[25].csa.hsum2 ),
    .Q(\genblk1[24].csa.y ),
    .RESET_B(_088_)
  );
  sky130_fd_sc_hd__dfrtp_1 _528_ (
    .CLK(clk),
    .D(_017_),
    .Q(\genblk1[25].csa.sc ),
    .RESET_B(_089_)
  );
  sky130_fd_sc_hd__dfrtp_1 _529_ (
    .CLK(clk),
    .D(\genblk1[26].csa.hsum2 ),
    .Q(\genblk1[25].csa.y ),
    .RESET_B(_090_)
  );
  sky130_fd_sc_hd__dfrtp_1 _530_ (
    .CLK(clk),
    .D(_018_),
    .Q(\genblk1[26].csa.sc ),
    .RESET_B(_091_)
  );
  sky130_fd_sc_hd__dfrtp_1 _531_ (
    .CLK(clk),
    .D(\genblk1[27].csa.hsum2 ),
    .Q(\genblk1[26].csa.y ),
    .RESET_B(_092_)
  );
  sky130_fd_sc_hd__dfrtp_1 _532_ (
    .CLK(clk),
    .D(_019_),
    .Q(\genblk1[27].csa.sc ),
    .RESET_B(_093_)
  );
  sky130_fd_sc_hd__dfrtp_1 _533_ (
    .CLK(clk),
    .D(\genblk1[28].csa.hsum2 ),
    .Q(\genblk1[27].csa.y ),
    .RESET_B(_094_)
  );
  sky130_fd_sc_hd__dfrtp_1 _534_ (
    .CLK(clk),
    .D(_020_),
    .Q(\genblk1[28].csa.sc ),
    .RESET_B(_095_)
  );
  sky130_fd_sc_hd__dfrtp_1 _535_ (
    .CLK(clk),
    .D(\genblk1[29].csa.hsum2 ),
    .Q(\genblk1[28].csa.y ),
    .RESET_B(_096_)
  );
  sky130_fd_sc_hd__dfrtp_1 _536_ (
    .CLK(clk),
    .D(_021_),
    .Q(\genblk1[29].csa.sc ),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _537_ (
    .CLK(clk),
    .D(\genblk1[30].csa.hsum2 ),
    .Q(\genblk1[29].csa.y ),
    .RESET_B(_034_)
  );
  sky130_fd_sc_hd__dfrtp_1 _538_ (
    .CLK(clk),
    .D(_023_),
    .Q(\genblk1[30].csa.sc ),
    .RESET_B(_035_)
  );
endmodule
